version: "2"
services:
  mautic:
    image: mautic/mautic
    depends_on:
      - mysql
    ports:
      - "80:80"
    environment:
      MAUTIC_DB_HOST: mysql
      MAUTIC_DB_USER: ${MYSQL_USER}
      MAUTIC_DB_PASSWORD: ${MYSQL_PASSWORD}
      MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data_mautic:/var/lib/mysql

  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ${PATH_CONF_FILE}/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mautic
    entrypoint:
      - "bash"
      - "-c"
    command: |
      "apt-get update && apt-get install openssl 
       openssl req -x509 -newkey rsa:2048 -sha256 -nodes -keyout /etc/ssl/private/mautic.key -out /etc/ssl/private/mautic.crt -subj '/CN=mautic.local' -days 3650
       echo 'Created new ssl certificate'
      exec nginx -g 'daemon off;'"
volumes:
  db_data_mautic:
      driver: rancher-nfs 
  sslcerts:

