version: "2"
services:
  jupyter:
    image: jupyter/all-spark-notebook
    ports:
      - ${PORT}:8888
    environment:
      GEN_CERT: "yes"
      GRANT_SUDO: "yes"
    command:
       start-notebook.sh
       --NotebookApp.password='sha1:29b153b69808:47e29b2173113ba478368371cc7efef05bc5068a' //password: hola
      

#    volumes:
#      - db_data_mautic:/var/lib/mysql
#
#volumes:
#  db_data_mautic:
#      driver: rancher-nfs 
