version: "2"
services:
  jupyter:
    image: jupyter/all-spark-notebook
    ports:
      - ${PORT}:8888
    environment:
      PASSWORD: ${PASSWORD}
      name: ${USER}

#    volumes:
#      - db_data_mautic:/var/lib/mysql
#
#volumes:
#  db_data_mautic:
#      driver: rancher-nfs 
