version: "2"
services:
  jupyter:
    image: jupyter/all-spark-notebook
    ports:
      - ${PORT}:8888
    environment:
      GEN_CERT: "yes"
      GRANT_SUDO: "yes"
    command:
       start-notebook.sh --NotebookApp.token='${PASSWORD}' 
      

#    volumes:
#      - db_data_mautic:/var/lib/mysql
#
#volumes:
#  db_data_mautic:
#      driver: rancher-nfs 
